/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

//import dao.Collectiondao;
import dao.DAOException;
import dao.Interfacedao;
import dao.ProductManagerdao;
import domain.Product;
import gui.helpers.SimpleListModel;
import java.math.BigDecimal;
import java.util.Collection;
import javax.swing.JOptionPane;
import net.sf.oval.ConstraintViolation;
import net.sf.oval.Validator;
import net.sf.oval.exception.ConstraintsViolatedException;

/**
 *
 * @author meani898
 */
public class ProductEditor extends javax.swing.JDialog {

	//create an instance of the DAO class
	private final Interfacedao store;
	private final SimpleListModel comboCategories = new SimpleListModel();
	//private final ProductManagerdao combo = new ProductManagerdao();

	/**
	 * Creates new form ProductEditor
	 */
	public ProductEditor(java.awt.Frame parent, boolean modal, Interfacedao dao) {
		super(parent, modal);
		store = dao;
		initComponents();
		categoryCombo.setEditable(true);

		Collection<String> categories = store.getCategories();
		comboCategories.updateItems(categories);
		categoryCombo.setModel(comboCategories);

	}

//	ProductEditor() {
//		throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      productLabel = new javax.swing.JLabel();
      txtID = new javax.swing.JTextField();
      nameLabel = new javax.swing.JLabel();
      nameTxt = new javax.swing.JTextField();
      descriptionLabel = new javax.swing.JLabel();
      jScrollPane1 = new javax.swing.JScrollPane();
      descriptionTxt = new javax.swing.JTextArea();
      categoryLabel = new javax.swing.JLabel();
      categoryCombo = new javax.swing.JComboBox<>();
      priceID = new javax.swing.JLabel();
      priceTxt = new javax.swing.JTextField();
      quantityLabel = new javax.swing.JLabel();
      quantityTxt = new javax.swing.JTextField();
      saveButton = new javax.swing.JButton();
      cancelButton = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

      productLabel.setText("Product ID:");

      txtID.setName("txtID"); // NOI18N
      txtID.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtIDActionPerformed(evt);
         }
      });

      nameLabel.setText("Name:");

      nameTxt.setName("nameTxt"); // NOI18N

      descriptionLabel.setText("Description:");

      descriptionTxt.setColumns(20);
      descriptionTxt.setRows(5);
      descriptionTxt.setName("descriptionTxt"); // NOI18N
      jScrollPane1.setViewportView(descriptionTxt);

      categoryLabel.setText("Category:");

      categoryCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
      categoryCombo.setName("categoryCombo"); // NOI18N
      categoryCombo.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            categoryComboActionPerformed(evt);
         }
      });

      priceID.setText("Price:");

      priceTxt.setName("priceTxt"); // NOI18N

      quantityLabel.setText("Quantity in Stock:");

      quantityTxt.setName("quantityTxt"); // NOI18N

      saveButton.setText("Save");
      saveButton.setName("saveButton"); // NOI18N
      saveButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            saveButtonActionPerformed(evt);
         }
      });

      cancelButton.setText("Cancel");
      cancelButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cancelButtonActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(productLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(descriptionLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(categoryLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(priceID, javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(quantityLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(txtID)
                     .addComponent(nameTxt)
                     .addComponent(priceTxt)
                     .addComponent(quantityTxt)))
               .addGroup(layout.createSequentialGroup()
                  .addGap(136, 136, 136)
                  .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE))
               .addGroup(layout.createSequentialGroup()
                  .addGap(136, 136, 136)
                  .addComponent(categoryCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(productLabel)
               .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(nameLabel)
               .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(descriptionLabel)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
            .addGap(3, 3, 3)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(categoryLabel)
               .addComponent(categoryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(priceID)
               .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(quantityLabel)
               .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(saveButton)
               .addComponent(cancelButton))
            .addGap(43, 43, 43))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

		 try {
			 String product = txtID.getText();
			 String name = nameTxt.getText();
			 String description = descriptionTxt.getText();
			 String category = (String) categoryCombo.getSelectedItem();

			 String priceStr = priceTxt.getText();
			 BigDecimal price = new BigDecimal(priceStr);

			 String quantityStr = quantityTxt.getText();
			 Integer quantity = new Integer(quantityStr);

			 //instance of products domain class and put variables inside prduct
			 Product prod = new Product();
			 prod.setProductID(product);
			 prod.setName(name);
			 prod.setDescription(description);
			 prod.setCategory(category);
			 prod.setListPrice(price);
			 prod.setQuantityInStock(quantity);

			 new Validator().assertValid(prod);

			 store.saveProduct(prod);
			 //will only print what is inside the toString method
			 System.out.println(prod);
			 dispose();
		 } catch (NumberFormatException nfe) {
			 JOptionPane.showMessageDialog(this,
						"You have entered a price or quantity that is not a valid number.",
						"Input Error", JOptionPane.ERROR_MESSAGE);
		 } catch (ConstraintsViolatedException ex) {
			 // get the violated constraints from the exception
			 ConstraintViolation[] violations = ex.getConstraintViolations();
			 // create a nice error message for the user
			 String msg = "Please fix the following input problems:";
			 for (ConstraintViolation cv : violations) {
				 msg += "\n •" + cv.getMessage();
			 }
			 // display the message to the user
			 JOptionPane.showMessageDialog(this, msg, "Input Error",
						JOptionPane.ERROR_MESSAGE);
		 } catch (DAOException ex) {
			 throw new DAOException(ex.getMessage(), ex);
		 }
    }//GEN-LAST:event_saveButtonActionPerformed

	//cancel button exits screen
   private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		dispose();
   }//GEN-LAST:event_cancelButtonActionPerformed

   private void categoryComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboActionPerformed
		// TODO add your handling code here:
   }//GEN-LAST:event_categoryComboActionPerformed

   private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtIDActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton cancelButton;
   private javax.swing.JComboBox<String> categoryCombo;
   private javax.swing.JLabel categoryLabel;
   private javax.swing.JLabel descriptionLabel;
   private javax.swing.JTextArea descriptionTxt;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JLabel nameLabel;
   private javax.swing.JTextField nameTxt;
   private javax.swing.JLabel priceID;
   private javax.swing.JTextField priceTxt;
   private javax.swing.JLabel productLabel;
   private javax.swing.JLabel quantityLabel;
   private javax.swing.JTextField quantityTxt;
   private javax.swing.JButton saveButton;
   private javax.swing.JTextField txtID;
   // End of variables declaration//GEN-END:variables
}
