package gui;

import dao.Interfacedao;

/**
 *
 * @author meani898
 */
public class ProductAdministration extends javax.swing.JFrame {

	private final Interfacedao dao;

	/**
	 * Creates new form ProductAdministration
	 */
	public ProductAdministration(Interfacedao dao) {
		initComponents();
		this.dao = dao;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      addProductJbutton = new javax.swing.JButton();
      viewJButton = new javax.swing.JButton();
      exitJbutton = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      addProductJbutton.setText("Add a New Product");
      addProductJbutton.setName("addProductJbutton"); // NOI18N
      addProductJbutton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            addProductJbuttonActionPerformed(evt);
         }
      });

      viewJButton.setText("View Products");
      viewJButton.setName("viewJButton"); // NOI18N
      viewJButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            viewJButtonActionPerformed(evt);
         }
      });

      exitJbutton.setText("Exit");
      exitJbutton.setName("exitJbutton"); // NOI18N
      exitJbutton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            exitJbuttonActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(exitJbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(viewJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(addProductJbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(77, 77, 77)
            .addComponent(addProductJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(viewJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(exitJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(75, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void exitJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitJbuttonActionPerformed
		System.exit(0);
   }//GEN-LAST:event_exitJbuttonActionPerformed

   private void addProductJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductJbuttonActionPerformed
		ProductEditor product = new ProductEditor(this, true, dao); //this is the parent, ture comtrols whether or not it is modal

		product.setVisible(true);

   }//GEN-LAST:event_addProductJbuttonActionPerformed

   private void viewJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewJButtonActionPerformed
		ViewProducts viewProd = new ViewProducts(this, true, dao);
		viewProd.setVisible(true);

   }//GEN-LAST:event_viewJButtonActionPerformed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton addProductJbutton;
   private javax.swing.JButton exitJbutton;
   private javax.swing.JButton viewJButton;
   // End of variables declaration//GEN-END:variables
}
