package gui;

import dao.Interfacedao;
import dao.ProductManagerdao;
import domain.Product;
import gui.helpers.SimpleListModel;
import java.util.Collection;
import javax.swing.JOptionPane;

/**
 *
 * @author meani898
 */
public class ViewProducts extends javax.swing.JDialog {

	//This model will hold all of the products that will be displayed. 
	private final SimpleListModel displayProducts = new SimpleListModel();
	private final SimpleListModel displayCategories = new SimpleListModel();

	private final Interfacedao store;

	/**
	 * Creates new form ViewProducts
	 */
	public ViewProducts(java.awt.Frame parent, boolean modal, Interfacedao dao) {
		super(parent, modal);
		store = dao;
		initComponents();

		//categoryFilterCombo.setEditable(true);
		//category combo box to display the categories of the products
		Collection<String> categories = store.getCategories(); //get the categories
		displayCategories.updateItems(categories);
		//categoryFilterCombo.setModel(displayProducts);
		categoryFilterCombo.setModel(displayCategories);

		Collection<Product> productsAll = store.getProducts();
		displayProducts.updateItems(productsAll);
		productList.setModel(displayProducts);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        productList = new javax.swing.JList<>();
        closeJButton = new javax.swing.JButton();
        searchLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        deleteJButton = new javax.swing.JButton();
        editJButton = new javax.swing.JButton();
        searchbyIDTxt = new javax.swing.JTextField();
        searchJButton = new javax.swing.JButton();
        categoryFilterCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        productList.setName("productList"); // NOI18N
        jScrollPane1.setViewportView(productList);

        closeJButton.setText("Close");
        closeJButton.setName("closeJButton"); // NOI18N
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });

        searchLabel.setText("Search by ID:");
        searchLabel.setName("searchLabel"); // NOI18N

        categoryLabel.setText("Category Filter:");
        categoryLabel.setName("categoryLabel"); // NOI18N

        deleteJButton.setText("Delete");
        deleteJButton.setName("deleteJButton"); // NOI18N
        deleteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJButtonActionPerformed(evt);
            }
        });

        editJButton.setText("Edit");
        editJButton.setName("editJButton"); // NOI18N
        editJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editJButtonActionPerformed(evt);
            }
        });

        searchbyIDTxt.setName("searchbyIDTxt"); // NOI18N

        searchJButton.setText("Search");
        searchJButton.setName("searchJButton"); // NOI18N
        searchJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchJButtonActionPerformed(evt);
            }
        });

        categoryFilterCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categoryFilterCombo.setName("categoryFilterCombo"); // NOI18N
        categoryFilterCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryFilterComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(editJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26)
                        .addComponent(deleteJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addComponent(closeJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(categoryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoryFilterCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchbyIDTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(searchJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLabel)
                    .addComponent(searchbyIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchJButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryLabel)
                    .addComponent(categoryFilterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButtonActionPerformed
		// TODO add your handling code here:
		dispose();
   }//GEN-LAST:event_closeJButtonActionPerformed


   private void deleteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJButtonActionPerformed

		//if no product is selected, do nothing
		if (productList.isSelectionEmpty()) {
		} else {

			Product selectedProduct = productList.getSelectedValue();
			//System.out.println("selectedProduct="+ selectedProduct);

			//Confimation dialog to see if user wants to delete the product
			int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this product?", "confirmation", JOptionPane.YES_NO_CANCEL_OPTION);

			// did the user click the yes button?
			if (result == JOptionPane.YES_OPTION) {
				// user clicked yes so perform the action

				//calling the delete product method from DAO class on the DAO field created in this class
				store.deleteProduct(selectedProduct);

				//update the JLists model object- needs to be all of the products not just one!
				displayProducts.updateItems(store.getProducts());
			}
		}
   }//GEN-LAST:event_deleteJButtonActionPerformed

   private void editJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJButtonActionPerformed
		// TODO add your handling code here:
   }//GEN-LAST:event_editJButtonActionPerformed

	// Search button takes the ID entered by the user and calls the search method in DAO
   private void searchJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchJButtonActionPerformed

		//retrieve the search ID entered by the user and save it in a variable
		String searchID = searchbyIDTxt.getText();

		//if nothing is entered do nothing and display nothing
		if (searchID.isEmpty()) {
		} else {
			//show the returned product and call the search method from DAO class
			Product returnedProduct = store.searchProduct(searchID);
			//update the JList with the returned product
			displayProducts.updateItems(returnedProduct);
		}
   }//GEN-LAST:event_searchJButtonActionPerformed
	//get the selected category and use it to call the DAO method to find the product
   private void categoryFilterComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryFilterComboActionPerformed

		//get the selected category: had to cast to String to fix error 
		String selectedCategory = (String) categoryFilterCombo.getSelectedItem();

		//call the DAO methd to find the associated products with that category
		Collection<Product> filteredCategoryProducts = store.filterCategories(selectedCategory);
		//update the JList's model-display the filtered products
		displayProducts.updateItems(filteredCategoryProducts);
   }//GEN-LAST:event_categoryFilterComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> categoryFilterCombo;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JButton closeJButton;
    private javax.swing.JButton deleteJButton;
    private javax.swing.JButton editJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Product> productList;
    private javax.swing.JButton searchJButton;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTextField searchbyIDTxt;
    // End of variables declaration//GEN-END:variables
}
