@startuml

' use strict UML mode
skinparam style strictuml

'Creating a user actor
actor "User" as user

'creating the Administration class
participant "Administration" as admin <<main>>
admin++

'Creating a main menu
create "Main Menu" as mainmenu <<JFrame>>
admin->mainmenu:construct
user->mainmenu++ : click "view products" button

'Creating the product editor screen dialog
create "View Products" as prodview <<dialog>>
mainmenu->prodview++ : construct

'Creating DAO
 create ProductManagerdao as dao <<DAO>>
 prodview->dao++ : construct
 
'get all of the products in the database
prodview->dao++: getProducts()

'database connection
create DbConnection as connection <<DAO>>
dao->connection++ : getConnection(uri);
connection->dao : connection
connection--

'sql statements get products
dao->dao: prepareStatement(sql)
dao->dao: executeQuery()
dao->dao: getters retrieve product details
dao->dao: setters set product details
dao->prodview: product
dao--

'update the list with the products
prodview->prodview: setModel(displayProducts)
prodview--

'viewer can see the products
prodview->user

'user choses a category
user->prodview++ : selects drop down option from combobox and clicks a category
prodview->prodview: CategoryFilterCombo.getSelectedItem()
prodview->dao++ : filterCategories(selectedCategory)

dao->connection++ : getConnection(uri);
connection->dao : connection
connection--

dao->dao: perpareStatement(sql)
dao->dao: setString(1, categoryChosen)
dao->dao: executeQuery()

dao->dao: getters retrieve product details
dao->dao: setters set product details
dao->prodview: products in chosen category (p)
dao--

'update dialog
prodview->prodview : updateItems(filteredCategoryProducts)

prodview->user: waiting for further user action
@enduml
